from .session import engine, SessionLocal, init_db, db_session, get_db, _to_utc_datetime, _datetime_for_db

from .models import (
    NotificationStatus,
    NotificationChannel,
    UserPreference,
    NotificationLog,
    NotificationTemplate,
    CaseDeadline,
    User,
    OTPVerification,
    Case,
    CaseNote,
    CaseNoteVersion,
)

from .crud.notifications import (
    create_case_deadline,
    get_upcoming_deadlines,
    get_prefs_by_user_ids,
    has_notification_been_sent,
    log_notification,
    get_notification_template_for_user,
    create_or_update_notification_template,
    update_notification_log_by_message_id,
    get_notification_history,
)
from .crud.knowledge import (
    record_knowledge_invalidation,
    list_knowledge_invalidations,
    get_knowledge_freshness_summary,
    process_due_knowledge_invalidations,
)
from .crud.feedback import submit_user_feedback, get_user_feedback

__all__ = [
    "engine",
    "SessionLocal",
    "init_db",
    "db_session",
    "get_db",
    "_to_utc_datetime",
    "_datetime_for_db",
    "NotificationStatus",
    "NotificationChannel",
    "UserPreference",
    "NotificationLog",
    "NotificationTemplate",
    "CaseDeadline",
    "User",
    "OTPVerification",
    "Case",
    "CaseNote",
    "CaseNoteVersion",
    "create_case_deadline",
    "get_upcoming_deadlines",
    "get_prefs_by_user_ids",
    "has_notification_been_sent",
    "log_notification",
    "get_notification_template_for_user",
    "create_or_update_notification_template",
    "update_notification_log_by_message_id",
    "get_notification_history",
    "submit_user_feedback",
    "get_user_feedback",
    "record_knowledge_invalidation",
    "list_knowledge_invalidations",
    "get_knowledge_freshness_summary",
    "process_due_knowledge_invalidations",
]
