"""
Row-Level Security (RLS) Migration for PostgreSQL

This script creates RLS policies on all tenant-scoped tables to enforce
database-level tenant isolation. It must be run against a PostgreSQL database
AFTER the initial schema migration (Base.metadata.create_all).

Usage:
    python -m scripts.setup_rls --dry-run  # preview SQL without applying
    python -m scripts.setup_rls             # apply RLS policies

Prerequisites:
    - PostgreSQL 9.5+ (RLS support)
    - Database user must have SUPERUSER or CREATEROLE privileges
    - All tables must exist before running this script

Tables protected:
    cases, case_deadlines, case_documents, case_timeline,
    attachments, users, notifications, notification_preferences,
    notification_templates, report_feedback, case_records,
    case_outcomes, model_feedback, user_feedback, case_analytics
"""

import argparse
import logging
import sys

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

RLS_TABLES = [
    ("cases", "user_id"),
    ("case_deadlines", "user_id"),
    ("case_documents", "user_id"),
    ("case_timeline", "user_id"),
    ("attachments", "user_id"),
    ("users", "id"),
    ("notifications", "user_id"),
    ("notification_preferences", "user_id"),
    ("notification_templates", "user_id"),
    ("report_feedback", "user_id"),
    ("case_records", "user_id"),
    ("case_outcomes", "user_id"),
    ("model_feedback", "user_id"),
    ("user_feedback", "user_id"),
    ("case_analytics", "user_id"),
    ("case_embeddings", "user_id"),
    ("case_issues", "user_id"),
    ("case_arguments", "user_id"),
]

STATEMENT_TIMEOUT = "SET statement_timeout = '30s';"

APPLY_RLS_TEMPLATE = """
-- Enable RLS on {table}
ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;

-- Drop existing policies for this table to allow re-running safely
DROP POLICY IF EXISTS tenant_isolation_{table} ON {table};

-- Create tenant isolation policy
-- Users can only see/modify rows where their user_id matches the table's user_id column
CREATE POLICY tenant_isolation_{table} ON {table}
    FOR ALL
    USING (
        CASE
            WHEN current_setting('app.current_user_id', true) IS NULL
                 OR current_setting('app.current_user_id', true) = ''
            THEN false
            ELSE {user_id_column} = current_setting('app.current_user_id')::integer
        END
    );

-- Allow public SELECT for users table (login/auth doesn't have user_id set yet)
{users_select_clause}

-- Force RLS for table owner as well to ensure policies apply to all connections
ALTER TABLE {table} FORCE ROW LEVEL SECURITY;
"""

USERS_SELECT_CLAUSE = """
-- Allow users table to be read without user_id context (for auth lookups)
CREATE POLICY tenant_isolation_{table}_auth ON {table}
    FOR SELECT
    USING ({user_id_column} = current_setting('app.current_user_id')::integer
           OR current_setting('app.current_user_id', true) IS NULL
           OR current_setting('app.current_user_id', true) = '');
"""


def generate_sql(dry_run: bool = False) -> list[str]:
    sql_statements = []

    sql_statements.append("--" + "=" * 78)
    sql_statements.append("-- Row-Level Security Migration")
    sql_statements.append("-- Generated by scripts/setup_rls.py")
    sql_statements.append("--" + "=" * 78)
    sql_statements.append("")

    sql_statements.append(STATEMENT_TIMEOUT)
    sql_statements.append("")

    for table, user_id_column in RLS_TABLES:
        if dry_run:
            logger.info(f"[DRY RUN] Would apply RLS to: {table} (user_id_column: {user_id_column})")
            continue

        is_users_table = table == "users"
        users_clause = USERS_SELECT_CLAUSE.format(
            table=table, user_id_column=user_id_column
        ) if is_users_table else ""

        statement = APPLY_RLS_TEMPLATE.format(
            table=table,
            user_id_column=user_id_column,
            users_select_clause=users_clause,
        ).strip()
        sql_statements.append(f"-- RLS for {table}")
        sql_statements.append(statement)
        sql_statements.append("")

    sql_statements.append("--" + "=" * 78)
    sql_statements.append("-- RLS Migration Complete")
    sql_statements.append("--" + "=" * 78)

    return sql_statements


def apply_rls_via_orm():
    """Apply RLS policies through SQLAlchemy connection (PostgreSQL only)."""
    try:
        from sqlalchemy import text
        from db.session import get_db_context, _is_sqlite
    except ImportError as e:
        logger.error(f"Failed to import db modules: {e}")
        sys.exit(1)

    if _is_sqlite:
        logger.warning("SQLite detected. RLS is PostgreSQL-only. Skipping.")
        return

    sql_statements = generate_sql(dry_run=False)
    with get_db_context() as db:
        for stmt in sql_statements:
            if not stmt.strip() or stmt.strip().startswith("--"):
                continue
            try:
                db.execute(text(stmt))
                logger.info(f"Applied: {stmt[:80]}...")
            except Exception as e:
                logger.error(f"Failed to apply statement: {e}")
                logger.error(f"Statement: {stmt[:200]}")
                db.rollback()
                raise

    logger.info("RLS policies applied successfully via database connection.")


def verify_rls() -> list[str]:
    """Query PostgreSQL system catalog to verify RLS is enabled."""
    query = """
    SELECT tablename, rowsecurity
    FROM pg_tables
    WHERE schemaname = 'public'
      AND tablename IN ({table_list})
    ORDER BY tablename;
    """.format(
        table_list=", ".join(f"'{t}'" for t, _ in RLS_TABLES)
    )

    try:
        from sqlalchemy import text
        from db.session import get_db_context, _is_sqlite
    except ImportError:
        return []

    if _is_sqlite:
        return []

    results = []
    with get_db_context() as db:
        result = db.execute(text(query))
        for row in result:
            results.append(f"  {row[0]}: rowsecurity={row[1]}")

    return results


def main():
    parser = argparse.ArgumentParser(
        description="Apply Row-Level Security (RLS) policies to tenant-scoped tables."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show SQL that would be applied without executing",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Verify RLS status on existing tables without applying",
    )
    args = parser.parse_args()

    if args.verify:
        results = verify_rls()
        if not results:
            print("Verify not supported (SQLite or import error)")
            sys.exit(0)
        print("RLS Status on protected tables:")
        for r in results:
            print(r)
        sys.exit(0)

    if args.dry_run:
        print("-- DRY RUN - No changes will be applied")
        print("")
        for stmt in generate_sql(dry_run=True):
            print(stmt)
        sys.exit(0)

    logger.info("Applying RLS policies...")
    try:
        apply_rls_via_orm()
        logger.info("Done. RLS policies are now active.")
    except SystemExit:
        raise
    except Exception as e:
        logger.error(f"RLS migration failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()